from typing import List, Literal
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_openai import ChatOpenAI
from langgraph.types import Command
from ..state import GraphState
from pydantic import BaseModel, Field
from langchain_core.tools import tool
from langgraph.graph import END
from langchain_core.messages import ToolMessage
from langgraph.prebuilt import ToolNode

class OrchestratorStructuredResponseTool(BaseModel):
    report: str = Field(description="Investigation agent final report after analysis")
    
class CodeChangeAgent:
    def __init__(self) -> None:
        # Use static methods as tools - this is the correct approach
        tools = [self.fetch_code_changes, OrchestratorStructuredResponseTool]
        self.tools = ToolNode(tools)
        # self.llm_with_tools = ChatGoogleGenerativeAI(model="gemini-2.0-flash", temperature=0.0).bind_tools(tools) # type: ignore
        # self.llm_with_tools = ChatGoogleGenerativeAI(model="gemini-1.5-flash", temperature=0.0).bind_tools(tools) # type: ignore
        self.llm_with_tools = ChatOpenAI(model="gpt-4o-mini", temperature=0.0).bind_tools(tools)
        self.system_prompt = (
            "You are the Code Change Analysis Agent in an automated AWS Lambda incident response system. "
            "Follow this EXACT workflow:\n"
            "1. When you receive a request, make ONE call to fetch_code_changes to gather data\n"
            "2. After receiving the data, IMMEDIATELY analyze it and create a report\n"
            "3. ALWAYS end your analysis by calling OrchestratorStructuredResponseTool with your report\n\n"
            "Your report MUST follow this format:\n"
            "- First line: 'This report is generated by Code Change Analysis agent'\n"
            "- Summary of findings\n"
            "- Recent deployments and changes\n"
            "- Risk assessment\n"
            "- Rollback recommendations\n\n"
            "Do NOT make more than one tool call before sending your report.\n"
            "IMPORTANT: You MUST call OrchestratorStructuredResponseTool after analyzing the data."
        )
        self.system_prompt_main = """
You are a Code Change Analysis Agent, a specialist component in an automated AWS Lambda incident response system. You work under the supervision of an Orchestrator Agent as part of a multi-agent workflow.

Your Role & Responsibility:
You are the "detective" of the incident response team - responsible for analyzing recent code changes, deployments, and configuration updates that might be related to AWS Lambda incidents. Your job is to identify if recent changes correlate with the incident timeline and could be potential root causes.

Workflow Context:
- You are called by the Orchestrator Agent with specific investigation requests about code changes
- You work in parallel with other specialist agents (System Analysis, History Retrieval)
- Your findings feed back to the Orchestrator who synthesizes all evidence for final resolution
- You may be called multiple times during an investigation as new questions arise

Available Tools:
1. fetch_code_changes: Retrieves and analyzes recent code changes, commits, and deployments
2. OrchestratorStructuredResponseTool: REQUIRED - Call this tool as your final step with your complete analysis report. This sends your findings back to the orchestrator.

Your Analysis Process:
1. UNDERSTAND THE REQUEST: Parse the Orchestrator's message to understand what code change investigation is needed
2. GATHER CHANGE DATA: Use fetch_code_changes to collect information about recent commits, deployments, and configuration changes
3. ANALYZE CHANGE PATTERNS: Look for:
   - Recent deployments around the incident timeline
   - Code changes in critical paths (error handling, database connections, API calls)
   - Configuration changes (environment variables, resource limits, permissions)
   - Dependency updates or library changes
   - Infrastructure-as-code modifications
4. CORRELATE WITH INCIDENT: Identify temporal correlations between changes and incident occurrence
5. ASSESS RISK: Evaluate which changes are most likely to cause the observed issues
6. FINAL STEP: Call the OrchestratorStructuredResponseTool with your complete analysis report

Key Guidelines:
- Be systematic: Check all types of changes (code, config, infrastructure, dependencies)
- Be temporal: Focus on changes made within 24-48 hours before the incident
- Be specific: Include commit IDs, timestamps, changed files, and deployment details
- Be risk-focused: Prioritize changes that affect critical functionality
- Consider rollback feasibility: Note if changes can be easily reverted

Response Format:
Structure your analysis clearly:
- **First line of your report**: "This report is generated by Code Change Analysis agent"
- **Summary**: One-line overview of your findings regarding recent changes
- **Recent Deployments**: List of deployments with timestamps and correlation to incident
- **Critical Code Changes**: Specific code modifications that could impact functionality
- **Configuration Changes**: Environment, resource, or permission changes
- **Risk Assessment**: Which changes are most likely to be the cause
- **Rollback Recommendations**: Specific steps to revert suspicious changes if needed

Examples of Good Analysis:
- "Deployment at 14:15 UTC (8 minutes before incident) introduced changes to database connection pooling. Modified timeout from 30s to 5s in connection.py, likely causing the observed timeout errors."
- "No deployments in last 24 hours, but infrastructure change at 13:00 UTC increased Lambda memory limit from 512MB to 128MB. This reduction could explain memory-related failures starting at 14:23 UTC."

Remember: You're providing change intelligence for the Orchestrator to make decisions. Focus on changes that could realistically cause the observed incident symptoms.
"""
    
    
    @staticmethod
    @tool
    async def fetch_code_changes(repo: str, commit_id: str) -> str:
        """Retrieves and analyzes recent code changes, deployments, and configuration updates for AWS Lambda incident investigation.
        
        This tool fetches comprehensive information about recent changes that could be related to the incident,
        including code commits, deployments, configuration modifications, and infrastructure changes. It performs
        analysis to identify changes that correlate with the incident timeline and could be potential root causes.
        
        Use this tool when you need to:
        - Investigate recent deployments around the incident timeline
        - Analyze code changes in critical functionality areas
        - Check for configuration or infrastructure modifications
        - Identify dependency updates or library changes
        - Correlate change timing with incident occurrence
        - Assess rollback feasibility for suspicious changes
        
        Args:
            repo (str): The repository name or identifier for the Lambda function.
                       Example: "my-lambda-repo" or "org/lambda-service"
            commit_id (str): Optional specific commit ID to analyze, or time-based reference.
                           Examples: "abc123def", "HEAD~5", "latest", "24h" (last 24 hours)
        
        Returns:
            str: Comprehensive change analysis including:
                - Recent deployment history with timestamps
                - Code changes in critical paths (database, API, error handling)
                - Configuration changes (environment variables, resource limits)
                - Infrastructure modifications (IAM roles, VPC settings, etc.)
                - Dependency updates and version changes
                - Risk assessment of each change relative to incident symptoms
                - Temporal correlation analysis between changes and incident
                - Rollback recommendations for high-risk changes
        
        Analysis Categories:
            - **Deployment Timeline**: When deployments occurred relative to incident
            - **Code Diff Analysis**: Specific lines changed in critical functionality
            - **Config Changes**: Environment variables, timeouts, memory limits, etc.
            - **Infrastructure Changes**: IAM permissions, VPC, security groups
            - **Dependency Analysis**: Library updates, version bumps, new packages
            - **Risk Scoring**: Likelihood each change could cause observed issues
        
        Example Usage:
            When investigating a Lambda timeout incident, call with the affected Lambda's repo
            to identify if recent changes to database connections, timeouts, or resource limits
            could explain the performance degradation.
        """
        # Mock realistic code changes for user-authentication-lambda timeout incident
        if "user-authentication" in repo.lower() or "auth" in repo.lower():
            code_changes_mock = f"""Code Change Analysis for {repo} (Reference: {commit_id}):

DEPLOYMENT HISTORY (Last 24 Hours):
• 2024-01-15 09:45:00Z - Deployment v2.1.3 (SUCCESSFUL)
  - Commit: a7f8b3c2 by sarah.dev@company.com
  - Pipeline: PROD-AUTH-LAMBDA-DEPLOY
  - No rollback detected

RECENT CODE CHANGES (Last 24 Hours):
📝 Commit a7f8b3c2 - "Optimize database connection pooling" (9 hours before incident)
  • File: src/database/connection_pool.py
  • Changes: Modified connection pool configuration
  • Lines Changed: 
    - Old: max_connections = 50, connection_timeout = 30
    - New: max_connections = 20, connection_timeout = 30
  • Risk Level: HIGH - Reduced connection pool size could cause bottlenecks

📝 Commit b2e9d1a5 - "Update authentication logic for improved security" (12 hours ago)
  • File: src/auth/validator.py  
  • Changes: Added additional database queries for user validation
  • Risk Level: MEDIUM - Additional DB queries could increase load

CONFIGURATION CHANGES:
• No environment variable changes detected
• No IAM permission changes in last 24 hours
• Lambda timeout remains at 30 seconds (unchanged)
• Memory allocation: 512MB (unchanged)

DEPENDENCY ANALYSIS:
• No package.json or requirements.txt changes
• No library version updates
• Database driver version unchanged (psycopg2==2.9.1)

INFRASTRUCTURE CHANGES:
• No VPC or security group modifications
• Database instance configuration unchanged
• No AWS Config rule violations

RISK ASSESSMENT:
🔴 HIGH RISK: Connection pool reduction (50→20) in commit a7f8b3c2
  - Temporal correlation: Change deployed 9 hours before incident
  - Impact: 60% reduction in available database connections
  - Likely cause of connection pool exhaustion observed in logs

🟡 MEDIUM RISK: Additional database queries in authentication logic
  - Could contribute to increased database load
  - May compound connection pool pressure

ROLLBACK RECOMMENDATION:
• IMMEDIATE ACTION: Revert commit a7f8b3c2 (connection pool changes)
• Command: Deploy previous version v2.1.2 or increase max_connections to 50
• ETA: 5-10 minutes for deployment
• Risk: Low rollback risk - only configuration change"""
        else:
            code_changes_mock = f"Code change analysis for repo '{repo}' (commit: {commit_id}): [Mock data - implement actual code change retrieval]"
        
        return code_changes_mock