from typing import List, Literal
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_openai import ChatOpenAI
from langgraph.types import Command
from ..state import GraphState
from pydantic import BaseModel, Field, constr
from langchain_core.tools import tool
from langgraph.graph import END
from langchain_core.messages import ToolMessage
from langgraph.prebuilt import ToolNode

class OrchestratorStructuredResponseTool(BaseModel):
    """Return the final code-change investigation report (Markdown) to the orchestrator."""
    report: constr(strip_whitespace=True, min_length=50, max_length=4000) = Field(
        description="Final Markdown report following the required headings and first-line tag."
    )
    
class CodeChangeAgent:
    def __init__(self) -> None:
        # Use static methods as tools - this is the correct approach
        tools = [self.fetch_code_changes, OrchestratorStructuredResponseTool]
        self.tools = ToolNode(tools)
        self.llm_with_tools = ChatGoogleGenerativeAI(model="gemini-2.0-flash", temperature=0.0).bind_tools(tools) # type: ignore
        # self.llm_with_tools = ChatGoogleGenerativeAI(model="gemini-1.5-flash", temperature=0.0).bind_tools(tools) # type: ignore
        # self.llm_with_tools = ChatOpenAI(model="gpt-4o-mini", temperature=0.0).bind_tools(tools)
        self.system_prompt = """
You are the Code Change Analysis Agent in an AWS Lambda incident workflow. Your job is to find change events (code, config, infra, deps) that plausibly explain the current symptoms and to return a concise Markdown report via OrchestratorStructuredResponseTool.

How to operate
- Parse the ask; extract service/repo, relevant function(s), and time window.
- Pull only what’s needed (commits, deployments, config/infra diffs) using fetch_code_changes.
- Be temporal and risk-focused: correlate change timestamps with the incident window; prioritize changes on critical paths (DB, timeouts, auth, network, IAM).
- Cite specifics: commit IDs, files, params, exact timestamps; avoid speculation.
- If evidence is insufficient, state what’s missing and the next data to query.
- End every run by calling OrchestratorStructuredResponseTool(report).

Report (Markdown)
- First line: "This report is generated by Code Change Analysis agent"
- Summary (one line)
- Recent Deployments (timeline + relevance to incident)
- Critical Code Changes (files/lines changed, rationale)
- Configuration/Infra Changes (env, timeouts, memory, IAM, VPC, SG)
- Risk Assessment (which change(s) most likely; why)
- Rollback Recommendations (specific steps or config reverts)

Micro-examples
- “List deployments and commits for auth repo last 48h; flag changes touching DB pooling or timeouts.”
- “Show config/infra diffs last 24h for my-lambda; note memory/timeout/IAM changes and deployment times.”
"""
        
    
    @staticmethod
    @tool
    async def fetch_code_changes(repo: str, commit_id: str) -> str:
        """Retrieves and analyzes recent code changes, deployments, and configuration updates for AWS Lambda incident investigation.
        
        This tool fetches comprehensive information about recent changes that could be related to the incident,
        including code commits, deployments, configuration modifications, and infrastructure changes. It performs
        analysis to identify changes that correlate with the incident timeline and could be potential root causes.
        
        Use this tool when you need to:
        - Investigate recent deployments around the incident timeline
        - Analyze code changes in critical functionality areas
        - Check for configuration or infrastructure modifications
        - Identify dependency updates or library changes
        - Correlate change timing with incident occurrence
        - Assess rollback feasibility for suspicious changes
        
        Args:
            repo (str): The repository name or identifier for the Lambda function.
                       Example: "my-lambda-repo" or "org/lambda-service"
            commit_id (str): Optional specific commit ID to analyze, or time-based reference.
                           Examples: "abc123def", "HEAD~5", "latest", "24h" (last 24 hours)
        
        Returns:
            str: Comprehensive change analysis including:
                - Recent deployment history with timestamps
                - Code changes in critical paths (database, API, error handling)
                - Configuration changes (environment variables, resource limits)
                - Infrastructure modifications (IAM roles, VPC settings, etc.)
                - Dependency updates and version changes
                - Risk assessment of each change relative to incident symptoms
                - Temporal correlation analysis between changes and incident
                - Rollback recommendations for high-risk changes
        
        Analysis Categories:
            - **Deployment Timeline**: When deployments occurred relative to incident
            - **Code Diff Analysis**: Specific lines changed in critical functionality
            - **Config Changes**: Environment variables, timeouts, memory limits, etc.
            - **Infrastructure Changes**: IAM permissions, VPC, security groups
            - **Dependency Analysis**: Library updates, version bumps, new packages
            - **Risk Scoring**: Likelihood each change could cause observed issues
        
        Example Usage:
            When investigating a Lambda timeout incident, call with the affected Lambda's repo
            to identify if recent changes to database connections, timeouts, or resource limits
            could explain the performance degradation.
        """
        # Mock realistic code changes for user-authentication-lambda timeout incident
        if "user-authentication" in repo.lower() or "auth" in repo.lower():
            code_changes_mock = f"""Code Change Analysis for {repo} (Reference: {commit_id}):

DEPLOYMENT HISTORY (Last 24 Hours):
• 2024-01-15 09:45:00Z - Deployment v2.1.3 (SUCCESSFUL)
  - Commit: a7f8b3c2 by sarah.dev@company.com
  - Pipeline: PROD-AUTH-LAMBDA-DEPLOY
  - No rollback detected

RECENT CODE CHANGES (Last 24 Hours):
📝 Commit a7f8b3c2 - "Optimize database connection pooling" (9 hours before incident)
  • File: src/database/connection_pool.py
  • Changes: Modified connection pool configuration
  • Lines Changed: 
    - Old: max_connections = 50, connection_timeout = 30
    - New: max_connections = 20, connection_timeout = 30
  • Risk Level: HIGH - Reduced connection pool size could cause bottlenecks

📝 Commit b2e9d1a5 - "Update authentication logic for improved security" (12 hours ago)
  • File: src/auth/validator.py  
  • Changes: Added additional database queries for user validation
  • Risk Level: MEDIUM - Additional DB queries could increase load

CONFIGURATION CHANGES:
• No environment variable changes detected
• No IAM permission changes in last 24 hours
• Lambda timeout remains at 30 seconds (unchanged)
• Memory allocation: 512MB (unchanged)

DEPENDENCY ANALYSIS:
• No package.json or requirements.txt changes
• No library version updates
• Database driver version unchanged (psycopg2==2.9.1)

INFRASTRUCTURE CHANGES:
• No VPC or security group modifications
• Database instance configuration unchanged
• No AWS Config rule violations

RISK ASSESSMENT:
🔴 HIGH RISK: Connection pool reduction (50→20) in commit a7f8b3c2
  - Temporal correlation: Change deployed 9 hours before incident
  - Impact: 60% reduction in available database connections
  - Likely cause of connection pool exhaustion observed in logs

🟡 MEDIUM RISK: Additional database queries in authentication logic
  - Could contribute to increased database load
  - May compound connection pool pressure

ROLLBACK RECOMMENDATION:
• IMMEDIATE ACTION: Revert commit a7f8b3c2 (connection pool changes)
• Command: Deploy previous version v2.1.2 or increase max_connections to 50
• ETA: 5-10 minutes for deployment
• Risk: Low rollback risk - only configuration change"""
        else:
            code_changes_mock = f"Code change analysis for repo '{repo}' (commit: {commit_id}): [Mock data - implement actual code change retrieval]"
        
        return code_changes_mock