import os
from typing import List, Literal
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.types import Command
from ..state import GraphState
from pydantic import BaseModel, Field
from langchain_core.tools import tool
from langgraph.graph import END
from langchain_core.messages import ToolMessage
from langgraph.prebuilt import ToolNode
from langchain_openai import ChatOpenAI

class OrchestratorStructuredResponseTool(BaseModel):
    report: str = Field(description="Investigation agent final report after analysis")


class InvestigationAgent:
    def __init__(self) -> None:
        # Use static methods as tools - this is the correct approach
        tools = [self.cloud_watch_logs_tools, self.lambda_metrics_tool, OrchestratorStructuredResponseTool]
        self.tools = ToolNode(tools)
        # self.llm_with_tools = ChatGoogleGenerativeAI(model="gemini-2.0-flash", temperature=0.0).bind_tools(tools) # type: ignore
        # self.llm_with_tools = ChatGoogleGenerativeAI(model="gemini-1.5-flash", temperature=0.0).bind_tools(tools) # type: ignore
        self.llm_with_tools = ChatOpenAI(model="gpt-4o-mini", temperature=0.0).bind_tools(tools)
        self.system_prompt = (
            "You are the Investigation Agent in an automated AWS Lambda incident response system. "
            "Follow this EXACT workflow:\n"
            "1. When you receive a request, make ONE or TWO calls to gather Lambda metrics or logs as needed.\n"
            "2. After receiving the data, IMMEDIATELY analyze it and create a report.\n"
            "3. ALWAYS end your analysis by calling OrchestratorStructuredResponseTool with your report.\n\n"
            "Your report MUST follow this format:\n"
            "- First line: 'This report is generated by Investigation Agent'\n"
            "- Summary of findings\n"
            "- Key Evidence\n"
            "- Metrics Analysis\n"
            "- Timing Correlation\n"
            "- Recommendations\n\n"
            "Do NOT make more than one tool calls before sending your report.\n"
            "IMPORTANT: You MUST call OrchestratorStructuredResponseTool after analyzing the data."
        )
        self.system_prompt_main = """
You are a Systems Analysis Agent, a specialist component in an automated AWS Lambda incident response system. You work under the supervision of an Orchestrator Agent as part of a multi-agent workflow.

Your Role & Responsibility:
You are the "eyes" of the incident response team - responsible for real-time analysis of AWS Lambda system state, metrics, and logs. Your job is to gather evidence from live systems to understand what's happening RIGHT NOW during an incident.

Workflow Context:
- You are called by the Orchestrator Agent with specific investigation requests
- You work in parallel with other specialist agents (Code Changes, History Retrieval)
- Your findings feed back to the Orchestrator who synthesizes all evidence for final resolution
- You may be called multiple times during an investigation as new questions arise

Available Tools:
1. cloud_watch_logs_tools: Retrieves and analyzes CloudWatch logs for specific Lambda functions
2. lambda_metrics_tool: Fetches and analyzes Lambda metrics (duration, errors, throttles, etc.)
3. OrchestratorStructuredResponseTool: REQUIRED - Call this tool as your final step with your complete analysis report. This sends your findings back to the orchestrator.

Your Analysis Process:
1. UNDERSTAND THE REQUEST: Parse the Orchestrator's message to understand exactly what investigation is needed
2. GATHER DATA: Use your tools systematically to collect relevant logs and metrics
3. ANALYZE PATTERNS: Look for:
   - Error patterns and frequencies
   - Performance anomalies (timeouts, memory issues)
   - Traffic spikes or drops
   - Correlation between metrics and timeline
4. SYNTHESIZE FINDINGS: Provide clear, actionable insights with evidence
5. FINAL STEP: Call the OrchestratorStructuredResponseTool tool to report back your analysis to the orchestrator agent

Key Guidelines:
- Be specific: Include timestamps, error codes, function names, and concrete data points
- Be evidence-based: Every conclusion should be backed by log entries or metric data
- Be concise but complete: Focus on relevant findings that help diagnose the incident
- Look for patterns: Single errors might be noise, but patterns indicate real issues
- Consider timing: Correlate when issues started with other system events

Response Format:
Structure your analysis clearly:
- **First line of your report**: "This report is generated by Investigation agent"
- **Summary**: One-line overview of your findings
- **Key Evidence**: Most important log entries, error patterns, or metric anomalies
- **Metrics Analysis**: Relevant performance data and trends
- **Timing Correlation**: When issues started/peaked relative to the incident timeline
- **Recommendations**: What additional investigation might be needed or immediate actions to consider

Examples of Good Analysis:
- "Lambda timeout errors increased 300% starting at 14:23 UTC, correlating with incident start time. Log analysis shows consistent 30-second timeouts in database connection pool initialization."
- "No errors in CloudWatch logs, but invocation duration shows 95th percentile increased from 200ms to 2.1s starting 2 hours before incident. Memory utilization peaked at 95% during slow periods."

Remember: You're providing raw intelligence for the Orchestrator to make decisions. Be thorough but focus on actionable insights that help identify the root cause.
"""

    @staticmethod
    @tool
    async def cloud_watch_logs_tools(service_id: str, from_time: str, to: str) -> str:
        """Retrieves and analyzes CloudWatch logs for AWS Lambda functions during incident investigation.
        
        This tool fetches CloudWatch logs for a specific Lambda function within a time range and performs
        initial analysis to identify error patterns, exceptions, and anomalies that could indicate the
        root cause of an incident.
        
        Use this tool when you need to:
        - Investigate specific error messages or stack traces
        - Analyze log patterns around the incident timeline
        - Look for recurring issues or anomalies in application logs
        - Validate hypothesis about specific error conditions
        
        Args:
            service_id (str): The AWS Lambda function name or ARN to retrieve logs for.
                            Example: "my-lambda-function" or "arn:aws:lambda:us-east-1:123456789012:function:my-function"
            from_time (str): Start time for log retrieval in ISO format or relative time.
                        Example: "2024-01-15T14:00:00Z" or "1h" (1 hour ago)
            to (str): End time for log retrieval in ISO format or relative time.
                     Example: "2024-01-15T16:00:00Z" or "now"
        
        Returns:
            str: Analyzed log data including error patterns, frequency analysis, and key findings.
                 The response includes filtered relevant log entries, error summaries, and
                 timing analysis to support incident diagnosis.
        
        Example Usage:
            When investigating a Lambda timeout incident, call with the affected function name
            and a time range covering the incident period to identify specific error patterns.
        """
        # Mock realistic CloudWatch logs for user-authentication-lambda timeout incident
        if "user-authentication" in service_id.lower():
            cloud_watch_mock = f"""CloudWatch Logs Analysis for {service_id} ({from_time} to {to}):

CRITICAL ERROR PATTERNS IDENTIFIED:
• 150 timeout events detected between 13:53:00Z - 14:23:00Z
• Pattern: Database connection pool exhaustion
• Error frequency: 5-8 timeouts per minute

KEY LOG ENTRIES:
[2024-01-15T14:22:45Z] ERROR: Connection timeout after 30s waiting for database connection
[2024-01-15T14:22:47Z] WARN: Connection pool exhausted (20/20 connections in use)
[2024-01-15T14:22:52Z] ERROR: Task timed out after 30.00 seconds
[2024-01-15T14:21:33Z] ERROR: psycopg2.OperationalError: connection timed out
[2024-01-15T14:20:15Z] WARN: Database query execution time: 28.5s (threshold: 30s)

ERROR ANALYSIS:
• Database connection timeouts: 89% of errors
• Memory allocation warnings: 11% of errors  
• No application logic errors detected
• Connection pool size appears insufficient for current load

TIMING CORRELATION:
• First timeout: 13:53:12Z
• Peak timeout rate: 14:15:00Z - 14:23:00Z (incident window)
• No timeouts observed before 13:53:00Z in last 24 hours"""
        else:
            cloud_watch_mock = f"CloudWatch logs analysis for {service_id} from {from_time} to {to}: [Mock data - implement actual log retrieval]"
        
        return cloud_watch_mock

    @staticmethod
    @tool
    async def lambda_metrics_tool(lambda_id: str, from_time: str, to: str) -> str:
        """Fetches and analyzes AWS Lambda performance metrics to identify system anomalies and performance issues.
        
        This tool retrieves comprehensive Lambda metrics from CloudWatch including invocation counts,
        duration, error rates, throttles, memory utilization, and concurrent executions. It performs
        statistical analysis to identify performance patterns and anomalies that could indicate incident causes.
        
        Use this tool when you need to:
        - Analyze Lambda performance trends and identify when issues started
        - Investigate timeout, memory, or concurrency-related problems  
        - Compare current performance against historical baselines
        - Identify correlation between metrics and incident timeline
        - Detect resource exhaustion or scaling issues
        
        Args:
            lambda_id (str): The AWS Lambda function name or ARN to analyze metrics for.
                           Example: "my-lambda-function" or "arn:aws:lambda:us-east-1:123456789012:function:my-function"
            from_time (str): Start time for metrics analysis in ISO format or relative time.
                        Example: "2024-01-15T14:00:00Z" or "2h" (2 hours ago)
            to (str): End time for metrics analysis in ISO format or relative time.
                     Example: "2024-01-15T16:00:00Z" or "now"
        
        Returns:
            str: Comprehensive metrics analysis including:
                - Performance trends (duration, memory usage, error rates)
                - Anomaly detection results with statistical significance
                - Baseline comparisons and percentage changes
                - Peak/valley identification with timestamps
                - Correlation analysis between different metrics
                - Actionable insights about resource constraints or performance degradation
        
        Key Metrics Analyzed:
            - Invocation count and rate
            - Duration (average, p95, p99, max)
            - Error count and rate
            - Throttle count and rate  
            - Memory utilization
            - Concurrent executions
            - Dead letter queue errors (if applicable)
        
        Example Usage:
            When investigating a performance degradation incident, call with the affected function
            and time range to identify if the issue is related to timeouts, memory limits, or scaling problems.
        """
        # Mock realistic Lambda metrics for user-authentication-lambda timeout incident
        if "user-authentication" in lambda_id.lower():
            lambda_metrics_mock = f"""Lambda Metrics Analysis for {lambda_id} ({from_time} to {to}):

PERFORMANCE SUMMARY:
• Function: user-authentication-lambda
• Region: us-east-1
• Analysis Period: Last 30 minutes (incident window)

CRITICAL METRICS IDENTIFIED:
Duration Metrics:
• Average Duration: 28.7s (baseline: 450ms) - 6280% increase
• P95 Duration: 30.0s (timeout threshold reached)
• P99 Duration: 30.0s (all requests timing out)
• Max Duration: 30.0s (Lambda timeout limit)

Error Metrics:
• Error Rate: 87.3% (baseline: 0.1%) - 87200% increase  
• Error Count: 150 errors in 30 minutes
• Timeout Errors: 150/150 (100% of errors are timeouts)
• No throttling detected

Invocation Metrics:
• Total Invocations: 172 (normal load)
• Successful Invocations: 22 (12.7%)
• Failed Invocations: 150 (87.3% - all timeouts)
• Concurrent Executions: Peak 8 (normal: 3-5)

Memory & Resource Metrics:
• Memory Utilization: 45% (512MB allocated)
• No memory pressure detected
• No cold start correlation with errors

TIMELINE ANALYSIS:
13:53:00Z - First timeout detected
14:00:00Z - Error rate escalated to 50%
14:15:00Z - Error rate reached 90%+ (incident peak)
14:23:00Z - Current time (ongoing incident)

ANOMALY DETECTION:
• CRITICAL: Duration increase of 6280% from baseline
• CRITICAL: Error rate spike from 0.1% to 87.3%
• Normal memory and concurrency patterns
• No scaling or cold start issues detected

CORRELATION ANALYSIS:
• Duration and error rate perfectly correlated (R²=0.98)
• No correlation with invocation volume
• Issue appears to be external dependency related (likely database)"""
        else:
            lambda_metrics_mock = f"Lambda metrics analysis for {lambda_id} from {from_time} to {to}: [Mock data - implement actual metrics retrieval and analysis]"
        
        return lambda_metrics_mock

