import os
from typing import List, Literal
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.tools import tool
from langchain_openai import ChatOpenAI
from langgraph.types import Command
from ..state import GraphState
from pydantic import BaseModel, Field, constr
from langchain_core.tools import tool
from langgraph.graph import END
from langgraph.prebuilt import ToolNode


class AnalysisInvestigationTool(BaseModel):
    """Investigate current system state: metrics, logs, runtime health for the specified Lambda(s). 
    Use for real-time diagnostics during an incident."""
    message: constr(strip_whitespace=True, min_length=10, max_length=300) = Field(
        description=(
            "Imperative, targeted instruction including scope and timeframe. "
            "Format: <action> for <service/function> over <time window> (+optional filters). "
            "Example: 'Analyze errors/latency for my-lambda last 24h; include p95/p99 and top log patterns.'"
        )
    )

class ChangeInvestigatorTool(BaseModel):
    """Analyze recent deployments, code/config changes that could correlate with the incident."""
    message: constr(strip_whitespace=True, min_length=10, max_length=300) = Field(
        description=(
            "Imperative, targeted instruction with scope + window. "
            "Example: 'List deployments/config updates for my-lambda past 7d; correlate with error spike timestamps.'"
        )
    )

class HistoryInvestigatorTool(BaseModel):
    """Retrieve similar past incidents and known fixes to inform triage."""
    message: constr(strip_whitespace=True, min_length=10, max_length=300) = Field(
        description=(
            "Imperative query describing the signature to match. "
            "Example: 'Find prior incidents with TimeoutError in my-lambda; summarize root causes and remediations.'"
        )
    )

class OrchestratorAgent():
    def __init__(self) -> None:
        tools = [AnalysisInvestigationTool, ChangeInvestigatorTool, HistoryInvestigatorTool, self.create_jira_ticket]
        self.tools = ToolNode(tools)
        self.llm_with_tools = ChatGoogleGenerativeAI(model="gemini-2.0-flash", temperature=0.0).bind_tools(tools)
        # self.llm_with_tools = ChatGoogleGenerativeAI(model="gemini-1.5-flash", temperature=0.0).bind_tools(tools) # type: ignore
        # self.llm_with_tools = ChatOpenAI(model="gpt-4o-mini", temperature=0.0).bind_tools(tools)
        self.system_prompt="""
You are the SRE **orchestrator** for AWS Lambda incidents. You supervise specialist agents (exposed as tools) and drive a brief, evidence-based investigation.

**Operate like this**

* **Round 1 (mandatory):** Immediately call `AnalysisInvestigationTool` and `ChangeInvestigatorTool` in parallel with concise, targeted prompts derived from `incident_context` (function, timeframe, signals).
* **Review → Decide:** Based strictly on tool evidence, either (a) synthesize and resolve, or (b) run **one** follow-up round. Use `HistoryInvestigatorTool` only if past incidents could inform the current one.
* **Max 2 rounds total.** Do not loop beyond that.
* **Always finish** by producing a Markdown report and calling `create_jira_ticket(report)`.

**Tool usage**

* Rely on each tool’s docstring for what it does. Keep each tool `message` imperative and specific (target, window, signals, filters). You may call multiple tools in one response.

**Report format (required)**

* **Incident Summary**
* **Evidence** (analysis, changes, history)
* **Root Cause Hypothesis**
* **Proposed Resolution** (fix + prevention)

**Rules**

* Base conclusions only on tool outputs; never invent facts.
* If evidence is insufficient after 2 rounds, state uncertainty and propose next steps, then file the ticket.

**Micro-examples**

* Analysis: “Analyze errors/timeouts for `my-lambda` in last 24h; include p95/p99 and recent log patterns.”
* Changes: “List deployments/config updates for `my-lambda` past 7d; flag anything near spike time.”
* History: “Find prior incidents with same error signature; summarize fixes.”
"""
        
    
    @staticmethod    
    @tool
    async def create_jira_ticket(report: str) -> str:
        """Creates a Jira ticket and attaches the investigation report.

        This tool is called by the orchestrator agent at the end of an investigation. It takes the
        final report, which is generated by the orchestrator, and uses it to create a new Jira ticket.

        Args:
            report (str): The final investigation report generated by the orchestrator.

        Returns:
            str: The ID of the created Jira ticket.
        """        
        # TODO: Implement actual Jira API call
        # Export the report to a Markdown file before creating the ticket
        import os
        from datetime import datetime
        
        print("=====================================")
        print('FINAL TOOL CALL GENERATING REPORT WITH TICKET')
        print("=====================================")

        # Create a directory for reports if it doesn't exist
        reports_dir = "incident_reports"
        if not os.path.exists(reports_dir):
            os.makedirs(reports_dir)

        # Generate a filename with timestamp
        timestamp = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
        filename = f"incident_report_{timestamp}.md"
        filepath = os.path.join(reports_dir, filename)

        # Write the report to the markdown file
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report)
        print(f"Exported investigation report to {filepath}")
        ticket_id = "JIRA-12345"  # Mock ticket ID
        print(f"Created Jira ticket {ticket_id}")
        return ticket_id, report
        
        
